### ISSUE TITLE
In https://github.com/davidgcameron/aCT expected path of aCTConfigARC.xml 

### ISSUE THREAD

**Issue by maikenp** [ARCControlTower/aCT#90]
Have not tested if this is the case also in the main repo, but on Davids fork: 

I have the aCTConfigARC.xml in folder:
$VIRTUAL_ENV/etc/act/
where $VIRTUAL_ENV=/home/centos/aCT

And then e.g. actstat works as expected, but actcriticalmonitor expects the file in /home/centos/aCT/bin/

```
(aCT) [centos@arc-client-docker-demo-remote ~]$ actstat -a
id jobname      JobID State arcstate 
------------------------------------
30 hello_docker ''    ''    ''       
49 hello_now7   ''    ''    ''       
50 hello_now1   ''    ''    ''  
```

```
(aCT) [centos@arc-client-docker-demo-remote ~]$ actcriticalmonitor
2 critical errors in the last hour

Last critical error:
[2020-08-20 08:56:08,505] [aCTProcess.py:95] [CRITICAL] - Traceback (most recent call last):
  File "/home/centos/aCT/src/act/common/aCTProcess.py", line 77, in run
    self.conf.parse()
  File "/home/centos/aCT/src/act/common/aCTConfig.py", line 15, in parse
    mtime=os.stat(self.configfile)[8]
FileNotFoundError: [Errno 2] No such file or directory: '/home/centos/aCT/bin/aCTConfigARC.xml'
```

For info, I have no $ACTCONFIGARC - not sure if that is supposed to be set when I activate the virtualenv?

**Comment by maikenp** [comment]
Invalid. I think this was an old error before I had moved the config-file to the actual new location in $VIRTUAL_ENV/etc/act - sorry :).
